### ISSUE TITLE
There is no utils.py file

### ISSUE THREAD

**Issue by wenhuazang** [ajayaraman/CarND-VehicleDetection#1]
hi, it is a great job and I learn a lot! When I saw your code, I have not found the utils.py files. Could you please upload your full code? Thank you very much!

**Comment by xugaoxiang** [comment]
Same problem.

**Comment by ajayaraman** [comment]
utils.py is from tensorflow's object detection library. To add this to your python path, please refer to tensorflow object detection api's installation instructions for [adding libraries to the python path ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#add-libraries-to-pythonpath)
