### ISSUE TITLE
Where is the label added? in vehicle_detection.ipynb

### ISSUE THREAD

**Issue by GitEasonXu** [ajayaraman/CarND-VehicleDetection#2]
## Where is the label added? 

```
batch_size = 256
train_datagen = ImageDataGenerator(
        shear_range=0.2,
        zoom_range=0.1,
        rotation_range=10.,
        horizontal_flip=True)

train_generator = train_datagen.flow_from_directory(
        'data',
        target_size=(64, 64),
        batch_size=batch_size)
```
Here you just use generator, But can't see where are you add `y_train` and `y_test` label, So can you explain it to me? Thank you.

**Comment by ajayaraman** [comment]
keras ImageDataGenerator uses the folder names under the /data and the /testdata folder as the labels. Therefore there is no explicit need to define the labels.

For this project code the /data and /testdata folders are setup with 2 sub-folders underneath 

/data
  /car
    car001.jpg
    car002.jpg
    ...
  /notcar
    notcar001.jpg
    ...

/testdata
 /car
 /notcar
